version: '3.7'

services:
  searxng:
    image: paulgoio/searxng:{ENV}
    restart: always
    networks:
      - proxy
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: loki
      options:
        loki-url: "${LOKI_URL}"
        loki-external-labels: env={ENV}
        loki-relabel-config: |
          - action: labeldrop
            regex: filename
    environment:
      - FILTRON=true
      - IMAGE_PROXY=true
      - DOMAIN={DOMAIN}
      - CONTACT=https://paulgo.io/#about
      - ISSUE_URL=https://github.com/paulgoio/searxng/issues
      - GIT_URL=https://github.com/paulgoio/searxng
      - GIT_BRANCH=main
    labels:
      - traefik.enable=true
      # router for static files
      - traefik.http.routers.{REPO}-static.rule=Host(`{DOMAIN}`)&&PathPrefix(`/static`)&&Method(`GET`,`HEAD`)
      - traefik.http.routers.{REPO}-static.entrypoints=https
      - traefik.http.routers.{REPO}-static.tls=true
      - traefik.http.routers.{REPO}-static.middlewares=external-secure,searx-csp@file,{REPO}-fp,{REPO}-static
      # router for dynamic files
      - traefik.http.routers.{REPO}.rule=Host(`{DOMAIN}`)&&Method(`GET`,`POST`,`HEAD`)
      - traefik.http.routers.{REPO}.entrypoints=https
      - traefik.http.routers.{REPO}.tls=true
      - traefik.http.routers.{REPO}.middlewares=external-secure,searx-csp@file,{REPO}-fp,{REPO}-dynamic
      # CSP for SearXNG in dynamic config
      # feature policy for SearXNG and morty
      - traefik.http.middlewares.{REPO}-fp.headers.customResponseHeaders.Permissions-Policy=accelerometer=();ambient-light-sensor=(); autoplay=();camera=();encrypted-media=();focus-without-user-activation=(); geolocation=();gyroscope=();magnetometer=();microphone=();midi=();payment=();picture-in-picture=(); speaker=();sync-xhr=();usb=();vr=()
      # cache control dynamic and static
      - traefik.http.middlewares.{REPO}-static.headers.customResponseHeaders.Cache-Control=public, max-age=31536000
      - traefik.http.middlewares.{REPO}-dynamic.headers.customResponseHeaders.Cache-Control=no-cache

networks:
  proxy:
    external: true
