version: '3.7'

services:
  morty:
    image: dalf/morty:latest
    restart: always
    command: -timeout 6
    read_only: true
    cap_drop:
      - ALL
    depends_on:
      - filtron
    networks:
      - proxy
      - default
    logging:
      driver: none
    labels:
      - traefik.enable=true
      - traefik.http.routers.{REPO}-morty.rule=Host(`{DOMAIN}`)&&PathPrefix(`/morty`)&&Method(`GET`,`HEAD`)
      - traefik.http.routers.{REPO}-morty.entrypoints=https
      - traefik.http.routers.{REPO}-morty.tls=true
      - traefik.http.routers.{REPO}-morty.middlewares=external-secure,{REPO}-morty-csp,{REPO}-fp,{REPO}-dynamic
      # CSP for morty
      - traefik.http.middlewares.{REPO}-morty-csp.headers.contentSecurityPolicy=default-src 'none'; style-src 'self' 'unsafe-inline'; form-action 'self'; frame-ancestors 'self'; base-uri 'self'; img-src 'self' data:; font-src 'self'; frame-src 'self'
    environment:
      - MORTY_KEY={KEY1}
      - MORTY_ADDRESS=0.0.0.0:3000
      - DEBUG=false

  filtron:
    image: paulgoio/filtron:production
    restart: always
    command: -listen 0.0.0.0:3000 -api 0.0.0.0:4041 -target searx:8080
    read_only: true
    cap_drop:
      - ALL
    depends_on:
      - searx
    networks:
      - default
      - proxy
    logging:
      driver: loki
      options:
        loki-url: "${LOKI_URL}"
        loki-external-labels: env={ENV}
        loki-relabel-config: |
          - action: labeldrop
            regex: filename
    labels:
      - traefik.enable=true
      # router for static files
      - traefik.http.routers.{REPO}-static.rule=Host(`{DOMAIN}`)&&PathPrefix(`/static`)&&Method(`GET`,`HEAD`)
      - traefik.http.routers.{REPO}-static.entrypoints=https
      - traefik.http.routers.{REPO}-static.tls=true
      - traefik.http.routers.{REPO}-static.middlewares=external-secure,searx-csp@file,{REPO}-fp,{REPO}-static
      # router for dynamic files
      - traefik.http.routers.{REPO}.rule=Host(`{DOMAIN}`)&&Method(`GET`,`POST`,`HEAD`)
      - traefik.http.routers.{REPO}.entrypoints=https
      - traefik.http.routers.{REPO}.tls=true
      - traefik.http.routers.{REPO}.middlewares=external-secure,searx-csp@file,{REPO}-fp,{REPO}-dynamic
      # CSP for searx in dynamic config
      # feature policy for searx and morty
      - traefik.http.middlewares.{REPO}-fp.headers.customResponseHeaders.Permissions-Policy=accelerometer=();ambient-light-sensor=(); autoplay=();camera=();encrypted-media=();focus-without-user-activation=(); geolocation=();gyroscope=();magnetometer=();microphone=();midi=();payment=();picture-in-picture=(); speaker=();sync-xhr=();usb=();vr=()
      # cache control dynamic and static
      - traefik.http.middlewares.{REPO}-static.headers.customResponseHeaders.Cache-Control=public, max-age=31536000
      - traefik.http.middlewares.{REPO}-dynamic.headers.customResponseHeaders.Cache-Control=no-cache

  searx:
    image: paulgoio/searx:{ENV}
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: loki
      options:
        loki-url: "${LOKI_URL}"
        loki-external-labels: env={ENV}
        loki-relabel-config: |
          - action: labeldrop
            regex: filename
    environment:
      - MORTY_KEY={KEY1}
      - DOMAIN={DOMAIN}
      - CONTACT=mailto:paul+searx@paulgo.io
      - ISSUE_URL=https://github.com/paulgoio/searx/issues
      - GIT_URL=https://github.com/paulgoio/searx
      - GIT_BRANCH=main

networks:
  proxy:
    external: true
